### ISSUE TITLE
無法正常訪問 blog

### ISSUE THREAD

**Issue by juishuyeh** [kyomind/kyomind.github.io#1]
Hi 版大好

訪問 https://blog.kyomind.tw/ 是正常結果。

點擊「閱讀更多」，都是全白畫面。

以下是附圖

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/8e942709-7b81-4fcf-abd9-464863e3d32d">

<img width="1024" alt="Snipaste_2024-10-18_21-12-30" src="https://github.com/user-attachments/assets/decb45f3-3bfd-4030-8f33-dfc21d48f014">

有使用過無痕開啟，還是一樣的結果。

**Comment by kyomind** [comment]
@juishuyeh 感謝告知🥹
應該是本機上的頁面快取有些問題，所以影響了部署結果
目前已修復，你可以再試試
再次感謝~

**Comment by juishuyeh** [comment]
已確認 OK，版大 poetry 相關文件是超棒的 handbook ，常常會回來查詢 ~ 非常感謝
